name: chililabs_gifsearch
description: "A gif search application using the Giphy service"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  flutter_staggered_grid_view: ^0.7.0

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  url_launcher: ^6.3.0
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.8.0
  mocktail: ^1.0.4

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env